title: Crimson
description: Trying my best
theme: jekyll-theme-midnight
markdown: kramdown

# show_downloads: False
# navigation:
#   - title: Home
#     url: /
#   - title: Write Ups
#     url: setup